src/creosote/parsers.py

This addresses the bug found in https://github.com/fredrikaverpil/creosote/issues/114#issuecomment-1455670134

fix: nonetype module causes crash

---

.gitignore
pyproject.toml
src/creosote/cli.py
src/creosote/parsers.py
src/creosote/resolvers.py
tests/conftest.py
tests/deps_files/requirements.txt
tests/test_cli.py

requirements.txt can contain lines which are not handled by the current parser. [pip-requirements-parser](https://pypi.org/project/pip-requirements-parser/) can handle rows like:
```
-i https://pypi.org/simple
-e git+https://github.com/psf/black.git@4a063a9#egg=black
```
I also updated the test fixtures to use a `try-yield-finally` pattern so that files get renamed back even when tests fail.
The change to `top_level_names` seemed to be necessary; I was getting an error like:
```
Traceback (most recent call last):
File "/Users/elijah/.asdf/installs/python/3.9.15/bin/creosote", line 8, in <module>
sys.exit(main())
File "/Users/elijah/Development/creosote/src/creosote/cli.py", line 90, in main
deps_resolver.resolve()
File "/Users/elijah/Development/creosote/src/creosote/resolvers.py", line …
```

Handle editable requirements

---

src/creosote/models.py
src/creosote/parsers.py
src/creosote/resolvers.py
tests/test_cli.py

This tries to fix the inability to find the package name of `gitpython`'s corresponding import name of `git`: https://github.com/fredrikaverpil/creosote/issues/123
The reason for the failure in #123 is that the `glob` is case sensitive.
With the changes in this PR, the issue with `gitpython`/`GitPython` mapping to `git` is fixed:
```bash
belay on  main is  v0.0.0 via  v3.11.2 (.venv)
❯ ../creosote/.venv/bin/creosote --venv .venv --paths belay --deps-file pyproject.toml --sections tool.poetry.dependencies
Parsing belay/webrepl.py
Parsing belay/device.py
Parsing belay/pyboard.py
Parsing belay/__init__.py
Parsing belay/hash.py
Parsing belay/inspect.py
Parsing belay/exceptions.py
Parsing belay/executers.py
Parsing belay/_minify.py
Parsing belay/typing.py
Parsing belay/helpers.py
Parsing …
```

fix: bad glob

---

src/creosote/models.py
src/creosote/resolvers.py

This should fix the issue where the package/import mapping for `typing-extensions`/`typing_extensions` could not be properly done. See #123 for more details.

feat: formalize gathering and association strategies

---

.pre-commit-hooks.yaml

Allows users to add to their `.pre-commit-config.yaml` file like:
```
- repo: https://github.com/fredrikaverpil/creosote
rev: v2.3.3
hooks:
- id: creosote
args:
- "--venv=.venv"
- "--paths=MY_PROJECT_PATH"
- "--deps-file=pyproject.toml"
- "--sections=tool.poetry.dependencies"
```
We can add this to the readme, but it might be annoying to update the `rev` in the readme when tagging new releases.

Natively support pre-commit: .pre-commit-hooks.yaml

---

src/creosote/parsers.py
src/creosote/resolvers.py

- Any issue was reported in #124 where `open()` calls did not succeed.
- Add `encoding="utf-8"` to all `open()` calls.
- 🤔 I'm a little concerned this will affect some systems, and cause similar issues, but where `utf-8` was not expected. Technically, this could mean this is a backwards-compatibility breaking change...?

Open files for reading with utf-8 encoding

---

README.md
src/creosote/cli.py
src/creosote/models.py
src/creosote/parsers.py
src/creosote/resolvers.py
tests/test_parsers.py

- #130 
- Added the `--exclude-deps` argument.
- Refactorings.
- I've been mixing terminologies... the README.md mentions dependencies _and_ packages interchangeably. Should probably settle on one of them and keep things consistent. This also applies to the source code. Doesn't need to part of this PR although it could affect the argument name;
- `--exclude-packages`
- `--exclude-dependencies`
- `--exclude-deps`

Exclude packages

---

src/creosote/cli.py
src/creosote/formatters.py
src/creosote/models.py
src/creosote/parsers.py
src/creosote/resolvers.py

- I've been very inconsistent in variable/function/class naming.
- Conformed terminology to talk about _dependencies_ (not e.g. _packages_) and various renaming.
- Added missing type definitions.
Bonus, while adding types:
- Noticed I was missing a return code when running `creosote --version`.
- Noticed I was adding `None` to the list to be returned by `load_pyproject_pep621`, so I added an if-statement and a warning log there.
- Noticed a hasattr(node, "names") was missing in `get_module_info_from_code`.
N/A

Conform to mentioning dependencies (not packages)

---

README.md
src/creosote/cli.py
src/creosote/resolvers.py
tests/test_cli.py

- I need a way to provide experimental features.
- In #153, thanks to @sanmai-NL, I realized creosote is wrongly identifying excluded-and-not-installed deps as unused, along with an exit code of 1. This is a bug.
- Excluded-and-not-installed deps are no longer considered "unused". If a dependency is found to be excluded (and not installed), a warning will still be shown but the error code will be 0.
- Add features "facility"  along with new argument `--use-feature`. This is btw how the other arguments should've been set up... something to keep in mind for v3.0.0, although a rather big change that will break things for a lot of users...
- Add features for passing/failing the check whether excluded-and-not-installed deps are found. It's likely that I can remove the one for passing, as this …

Excluded deps (and not installed) should not count towards unused dependencies

---

README.md
src/creosote/cli.py
src/creosote/parsers.py
src/creosote/resolvers.py

Currently, a somewhat weird way of suppliying multiple values to the same argument is being used.
```bash
creosote -p somefile1.py somefile2.py
```
- Use the more common (?) pattern of allowing for repeated definitions of the same argument (requires `v3-args` feature, since this would be backwards compatibility breaking behavior). Example:
```bash
creosote --use-feature v3-args  -p somefile1.py -p somefile2.py
```
- Make it possible to specify multiple virtual environments using multiple `--venv` arguments.
None.

Add feature for new arguments specification

---

.github/workflows/publish.yml

Use trusted publishing: https://github.com/pypa/gh-action-pypi-publish
Update the GHA workflow.
N/A

Add trusted publishing

---

.github/workflows/check.yml
.github/workflows/test.yml

Python 3.12 is already at alpha 7.
Add Python 3.12 to the ci.
N/A

feat: use Python 3.12-dev for ci

---

README.md
src/creosote/parsers.py

Currently, users of PEP-582 who wish to use creosote and point it to the `__pypackages__` folder instead of a venv cannot do this currently.
Update the regexp which used to assume a "site-packages" folder.
- Could be a bit slower, but likely not noticeable...
- Closes #169

fix: do not assume site-packages folder name

---

src/creosote/parsers.py
tests/deps_files/Pipfile
tests/fixtures/fast.py
tests/test_parsers.py

It appears there's a bug when using pipenv / `Pipfile`: #173 
- Read Pipfile properly.

Fix pipenv/Pipfile support

---

src/creosote/parsers.py
tests/deps_files/pyproject.pep621.toml
tests/deps_files/pyproject.poetry.toml
tests/test_parsers.py

When adding tests, I noticed that e.g. `project.optional-dependencies` are not handled correctly, if provided.
Add different parsing based on whether value of given toml section is of type `list` vs `dict`.
None.

Handle pep621 dependencies when defined as dict

---

pyproject.toml
src/creosote/resolvers.py
tests/fixtures/manual.py

This is a very short-term solution to just avoid having ruff break CI all the time, since each release brings new linting rules.
For example, dependabot PR break because ruff is not pinned/configured to run the same way on the code base: https://github.com/fredrikaverpil/creosote/pull/178
Hard-pin `ruff`. Let's rely on dependabot for updates of it instead.
The same problem applies to mypy and black, but they are not backwards-breaking compat as often. Wouldn't it have been nice if there was a native lockfile mechanism to pip/pyproject.toml ... 🤡

chore: pin ruff to avoid CI breakage

---

renovate.json

This just removes the ability to use renovate to update dependencies. Instead I'll rely on the already existing dependabot configuration.

chore: remove renovate, rely on dependabot instead

---

.github/dependabot.yml

Dependabot can be chatty about updates, especially for `ruff`, which is actively developed. This change just avoids noise for me.
Set dependabot's checking interval of dependency updates to `monthly`.
Nope.

chore: update dependabot interval to monthly

---

src/creosote/parsers.py

When e.g. `creosote --exclude-dep dotty-dict` is entered, there is a false warning about "Excluded dependencies not found in virtual environment: dotty-dict".
```bash
$ creosote --exclude-dep dotty-dict             
Found dependencies in pyproject.toml: loguru, pip-requirements-parser, toml
Excluded dependencies not found in virtual environment: dotty-dict
No unused dependencies found! ✨
```
The reason for this is that the entered dependency name was not canonicalized as `dotty_dict`.
Canonicalize the dependency name when performing this check.
No.

Fix bug which could give a false warning

---

src/creosote/config.py

Following the change in #182, the custom append action for arguments couldn't find the default value of an argument. This lead to that it was unable to remove the default value from lists.
This meant that the default item(s) in the default lists remained even if the user defined other values.
So for example, `[project.dependencies]` were always attempted to be read, even if the user entered `--section tool.poetry.dependencies`. Same with `--path` which always tried to access a `src` folder.
Define a default value for each argument where the `CustomAppendAction` is used. To keep it consistent, I'll just add the default value to all arguments that have one.
Hopefully not.

Fix bug where CustomAppendAction would not work properly

---

tests/fixtures/integration.py

Turns out that the temporary folder was not removed after each test.
Add cleanup.
None.

Add test cleanup

---

.github/workflows/check.yml
.github/workflows/test.yml

I'm using `3.12-dev` but now that Python 3.12 was officially released, I shouldn't be using an in-development version.
Change from `3.12-dev` to `3.12` in GHA.
None.

Use Python 3.12 in CI

---

.github/dependabot.yml
pyproject.toml
src/creosote/config.py
tests/conftest.py
tests/test_integration.py

CI is failing due to ruff not being pinned.
- Update and pin ruff (will be updated by dependabot).
- Fix the pyproject.toml ruff warnings.
- Run `ruff format`.
- Run `ruff check --fix`.
- Set dependabot frequence to monthly (while I'm at it).
None.

Fix failing ci/linting

---

src/creosote/resolvers.py
tests/test_integration.py

Fixes #205
To sum it up, ruamel.yaml has a period sign in its dependency name and in the folderpath and its RECORD file. This was not previously supported.
- Update regexp pattern for matching filepaths, so to support period signs.
- Looks for dependencies with raw name (e.g. ruamel.yaml) in `RECORD` files. Previously, the dependency name was "canonicalized" so that e.g. a period sign was converted into an underscore.
- Adds a test for ruamel.yaml.
Try it out:
```bash
$ pipx install --suffix=@206 --force git+https://github.com/fredrikaverpil/creosote.git@refs/pull/206/head
$ creosote@206 --venv .venv ...
$ pipx uninstall creosote@206
```

Support period sign in dependency name

---

README.md
pyproject.toml
src/creosote/parsers.py
tests/notebook.ipynb
tests/test_integration.py
tests/test_integration_notebook.py

This PR adds support for parsing and recognizing dependencies in Jupyter notebooks, which can be helpful in notebook-heavy workflows where some dependencies are only used in notebooks but shouldn't be counted as unused.
- Adds two dependencies needed for converting .ipynb files to .py
- Adds .ipynb files to the list of files to be parsed for module names
- Adds logic to `get_module_info_from_python_file()` such that if the current file is a .ipynb, use `nbconvert` to convert the notebook to a temporary file, then parse that file for dependencies as usual.
A couple small flags:
- There's a more elegant way of handling the temporary file creation + deletion using tempfile's `delete_on_close` parameter, but this is only supported in Python 3.12+ so I left it out.  Happy to make other changes …

Add .ipynb files to parser file search

---

src/creosote/resolvers.py

Bug described and reproduced in #205.
The import name found in the top_level.txt or RECORD files was not accurately compared against the dependency name. The latter had been canonicalized whereas the former had not.
@sanmai-NL thanks for persistently poking me about this. I believe it's finally fixed. You can try it out like so:
```bash
$ pipx install --suffix=@222 --force git+https://github.com/fredrikaverpil/creosote.git@refs/pull/222/head
$ creosote@222 --venv .venv ...
$ pipx uninstall creosote@222
```

fix: compare using canonicalization

---

.github/workflows/test.yml
README.md
pyproject.toml
src/creosote/config.py
src/creosote/parsers.py
tests/deps_files/pyproject.pep735.toml
tests/test_dependency_reader.py
tests/test_integration.py

fixes #221
⚠️ it might be good to bump Creosote to 4.0 following this change (replacing the toml library) 🤔 and if so, it would be good to take advantage of this so also to move from `v1.2.3` -> `1.2.3` release tags (for release-please).

feat(parser): add PEP-735 support for dependency-groups

---

.github/dependabot.yml

Dependabot can now handle `uv`.
- Add beta directive.
- Replace `pip` eco system with `uv`.
- See more: https://github.com/dependabot/dependabot-core/issues/10478#issuecomment-2691330949

ci: use uv instead of pip

---

.github/workflows/sync.yml

This PR syncs the GitHub repo with CI workflows from the [fredrikaverpil/github](https://github.com/fredrikaverpil/github) repository.

ci(workflows): sync with fredrikaverpil/github

---

src/creosote/resolvers.py
tests/fixtures/integration.py
tests/test_integration.py

Issue found in #274 where version suffix `rc1` is not detected properly by internal regular expressions (this is a very good catch).
- Update regexp with ["official" regexp](https://packaging.python.org/en/latest/specifications/version-specifiers/#appendix-parsing-version-strings-with-regular-expressions)
I don't think so.

fix: version suffix not supported by regexp
