fredrikaverpil/creosote

src/creosote/cli.py
**Why** is the change needed?
Inspired by `git status --porcelain`, this flag allows users to specify that they want the output in a terse, parse-able format. Allows for doing something like the following.
```sh
creosote --porcelain | xargs poetry remove
```
**How** is the need addressed?
- Add an optional flag `--porcelain`.
- When that flag is on:
- Set logging LEVEL to `critical`, effectively disabling all logs.
- Use a print statement to output a terse output for easy parsing.
What **side-effects** could the change have?
- This was done rather hastily. Maybe I should have refactored the
solution. :innocent:
=> feat(logging): Add porcelain CLI flag

src/creosote/cli.py, src/creosote/formatter.py
@JRasmusBm added a formatter here :)
(I really need to add a tests suite next)
=> Add formatter

pyproject.toml, src/creosote/parsers.py, src/creosote/resolvers.py, tests/conftest.py, tests/deps_files/pyproject.pep621.toml, tests/deps_files/pyproject.poetry.toml, tests/deps_files/requirements.txt, tests/test_cli.py, tests/test_parsers.py
=> feat: add git link support

src/creosote/cli.py, src/creosote/formatters.py, src/creosote/parsers.py
Also ended up fixing some general typing issues as well as adding pipenv/Pipfile support in this PR.
=> Add more debug logging

.github/workflows/test.yml, README.md, src/creosote/cli.py, src/creosote/formatters.py, src/creosote/parsers.py, src/creosote/resolvers.py, tests/deps_files/pyproject.pep621.toml, tests/deps_files/pyproject.poetry.toml, tests/deps_files/requirements.txt, tests/test_cli.py
- Needed to polish the docs and the logging a bit.
- fix: use .venv in CI
- try: replacing idna with typing-extensions
- feat: update logging and docs
- None.
=> docs: update logging and docs

src/creosote/cli.py, src/creosote/formatters.py, src/creosote/resolvers.py
- Turns out an exit code was not set! 😱
- Set the exit code based on success... like it should've done from day 1.
N/A
=> Return exit code 0 or 1

src/creosote/cli.py, src/creosote/parsers.py, src/creosote/resolvers.py
- The `main` entrypoint function was a bit messy. Some unclear function responsibilities and logging scattered throughout.
- Refactor out responsibilities, making the `main` a lot less verbose and to the point.
- Refactor logging out into each function that should log.
None.
=> Clean up main function, move logging

src/creosote/resolvers.py
=> fix: redundant expression

src/creosote/config.py, tests/test_custom_append_action.py
This is an alternative proposal to #188. They aren't mutually exclusive, so you can pick/choose depending on what you prefer.
=> Fix custom append action

tests/test_integration.py
When refactoring the CLI / integration tests, I forgot about the requirementst.txt file. I noticed this when looking at the test coverage.
Add the missing test case parameters.
Nope.
=> Add missing test case for requirementst.txt file

tests/test_integration.py
Let's extend the existing test with more repeated arguments.
Extended the existing test to cover repeated uses of `--section` and `--exclude-dep`.
None.
=> Extend test with more repeated args

tests/test_integration.py
Move the appropriate parts into the arrange, act and assert "sections".
=> Test cleanup

src/creosote/config.py, src/creosote/parsers.py, src/creosote/resolvers.py
=> fix: avoid UnicodeDecodeError

src/creosote/cli.py, src/creosote/config.py
=> fix: fail fast when deps file (-d) is not found

src/creosote/parsers.py, tests/deps_files/Pipfile
=> fix: support dependency spec where version can either be str or dict

.github/workflows/sync.yml
=> ci(sync): add sync

.github/workflows/sync.yml
This PR syncs the GitHub repo with CI workflows from the [fredrikaverpil/github](https://github.com/fredrikaverpil/github) repository.
=> ci(workflows): sync with fredrikaverpil/github

.github/workflows/managed-releaseplease.yml
=> ci: pass token explicitly

src/creosote/parsers.py, tests/test_integration.py
=> fix(poetry): support list

.github/workflows/unmanaged-dependabot.yml
=> ci(dependabot): generate dependabot.yml
